default[:warp][:user] = "vagrant"
default[:warp][:group] = "vagrant"
default[:warp][:pid_file] = "/home/vagrant/twistd.pid"
default[:warp][:log_file] = "/home/vagrant/twistd.log"
default[:warp][:version] = ""
